### ISSUE TITLE
EOFError: read() didn't return enough bytes

### ISSUE THREAD

**Issue by FahrulRPutra** [hkociemba/RubiksCube-TwophaseSolver#11]
2020-12-02T12:49:17.639736+00:00 app[web.1]: loading conj_twist table...
2020-12-02T12:49:17.640385+00:00 app[web.1]: loading conj_ud_edges table...
2020-12-02T12:49:17.643817+00:00 app[web.1]: loading flipslice sym-tables...
2020-12-02T12:49:17.648517+00:00 app[web.1]: Traceback (most recent call last):
2020-12-02T12:49:17.648585+00:00 app[web.1]:   File "start_server.py", line 3, in <module>
2020-12-02T12:49:17.648830+00:00 app[web.1]:     import sockets
2020-12-02T12:49:17.648859+00:00 app[web.1]:   File "/app/sockets.py", line 6, in <module>
2020-12-02T12:49:17.649051+00:00 app[web.1]:     import solver
2020-12-02T12:49:17.649100+00:00 app[web.1]:   File "/app/solver.py", line 5, in <module>
2020-12-02T12:49:17.649299+00:00 app[web.1]:     import symmetries as sy
2020-12-02T12:49:17.649337+00:00 app[web.1]:   File "/app/symmetries.py", line 217, in <module>
2020-12-02T12:49:17.649690+00:00 app[web.1]:     flipslice_rep.fromfile(fh, N_FLIPSLICE_CLASS)
2020-12-02T12:49:17.649745+00:00 app[web.1]: EOFError: read() didn't return enough bytes

So i'am trying to use this on heroku but this error occurs

**Comment by hkociemba** [comment]
I assume that on writing some file something went wrong and when reading back the file was incomplete or missing. Deleting all created files and rerunning should fix the problem.

**Comment by jm493** [comment]
I hit this problem in CUBOTino https://github.com/AndreaFavero71/CUBOTino_base_version/issues/4

Different architectures use 4 or 8 bytes for a `'L'` array, so tables created on one architecture can't be distributed to everyone.

What do you think of testing for what type of array to use for a uint32 ?
Something like:
```
if ar.array('I').itemsize >= 4:
   ar_uint32 = 'I'
else:
  ar_uint32 = 'L'
...
    flipslice_rep = ar.array(ar_uint32, [0] * N_FLIPSLICE_CLASS)  # classidx -> idx of representant
...
    flipslice_rep = ar.array(ar_uint32)
```

**Comment by jm493** [comment]
The changes for version 1.1.1 have fixed this problem.
Thanks.
