### ISSUE TITLE
list index out of range

### ISSUE THREAD

**Issue by chester4444** [hkociemba/RubiksCube-TwophaseSolver#2]
Hi, i tried to solve some cubes on a raspberry with your great software on a raspberry.

here is what i get when i send this to the server:
 echo DDDDUDDDDRRRRRRRRRBBBBFBBBBUUUUDUUUULLLLLLLLLFFFFBFFFF |nc 127.0.0.1 8080

pi@raspberrypi:~/RubiksCube-TwophaseSolver $ python3 start_server.py
```
loading conj_twist table...
loading conj_ud_edges table...
loading flipslice sym-tables...
loading move_twist table...
loading move_flip table...
loading move_slice_sorted table...
loading move_u_edges table...
loading move_d_edges table...
loading move_ud_edges table...
loading move_corners table...
loading phase1_prun table...
loading phase2_prun table...
loading phase2_cornsliceprun table...
startserver
Server socket created
Server now listening...
Connected with 127.0.0.1:40968, 2017.10.28  12:16:34
Exception in thread Thread-3:
Traceback (most recent call last):
  File "/usr/lib/python3.4/threading.py", line 920, in _bootstrap_inner
    self.run()
  File "/home/pi/RubiksCube-TwophaseSolver/solver.py", line 193, in run
    self.search(self.co_cube.flip, self.co_cube.twist, self.co_cube.slice_sorted, dist, togo1)
  File "/home/pi/RubiksCube-TwophaseSolver/solver.py", line 114, in search
    m = self.sofar_phase1[-1]
IndexError: list index out of range

Exception in thread Thread-2:
Traceback (most recent call last):
  File "/usr/lib/python3.4/threading.py", line 920, in _bootstrap_inner
    self.run()
  File "/home/pi/RubiksCube-TwophaseSolver/solver.py", line 193, in run
    self.search(self.co_cube.flip, self.co_cube.twist, self.co_cube.slice_sorted, dist, togo1)
  File "/home/pi/RubiksCube-TwophaseSolver/solver.py", line 114, in search
    m = self.sofar_phase1[-1]
IndexError: list index out of range

Exception in thread Thread-4:
Traceback (most recent call last):
  File "/usr/lib/python3.4/threading.py", line 920, in _bootstrap_inner
    self.run()
  File "/home/pi/RubiksCube-TwophaseSolver/solver.py", line 193, in run
    self.search(self.co_cube.flip, self.co_cube.twist, self.co_cube.slice_sorted, dist, togo1)
  File "/home/pi/RubiksCube-TwophaseSolver/solver.py", line 114, in search
    m = self.sofar_phase1[-1]
IndexError: list index out of range

DDDDUDDDDRRRRRRRRRBBBBFBBBBUUUUDUUUULLLLLLLLLFFFFBFFFF
Connection closed
```
Even a already solved cube results in a server error

`echo UUUUUUUUURRRRRRRRRFFFFFFFFFDDDDDDDDDLLLLLLLLLBBBBBBBBB |nc 127.0.0.1 8080
`
```
pi@raspberrypi:~/RubiksCube-TwophaseSolver $ python3 start_server.py
loading conj_twist table...
loading conj_ud_edges table...
loading flipslice sym-tables...
loading move_twist table...
loading move_flip table...
loading move_slice_sorted table...
loading move_u_edges table...
loading move_d_edges table...
loading move_ud_edges table...
loading move_corners table...
loading phase1_prun table...
loading phase2_prun table...
loading phase2_cornsliceprun table...
startserver
Server socket created
Server now listening...
Connected with 127.0.0.1:40972, 2017.10.28  12:23:35
Exception in thread Thread-2:
Traceback (most recent call last):
  File "/usr/lib/python3.4/threading.py", line 920, in _bootstrap_inner
    self.run()
  File "/home/pi/RubiksCube-TwophaseSolver/solver.py", line 193, in run
    self.search(self.co_cube.flip, self.co_cube.twist, self.co_cube.slice_sorted, dist, togo1)
  File "/home/pi/RubiksCube-TwophaseSolver/solver.py", line 114, in search
    m = self.sofar_phase1[-1]
IndexError: list index out of range

UUUUUUUUURRRRRRRRRFFFFFFFFFDDDDDDDDDLLLLLLLLLBBBBBBBBB
Connection closed

```
What am i doing wrong here, thanks, chester

**Comment by hkociemba** [comment]
I really do not know what causes your problem. It is quite a long time since you reported the problem. Could you track it down meanwhile?

**Comment by hkociemba** [comment]
I closed this issue because of lacking response.
